### PR TITLE
Remove unneeded patches. The kern.proc.pathname sysctl works correctly.

### PR DESCRIPTION
**Pull request by ivadasz**

### CODE REVIEW

**Comment by jrmarino** [comment]
Does kern.proc.pathname work on DragonFly 3.6 and 3.8? (my guess is no)  Those are still supported.

**Comment by jrmarino** [comment]
although to be fair, it's probably a moot point with chromium since only dev branch and 4.0 has any chance of running.  (and 3.6 is not supported anymore)

**Comment by ivadasz** [comment]
kern.proc.pathname is missing in 3.6.
But it is included since 3.8, and there weren't any apparent changes to it since then (except the proc_usermap stuff), so I'd expect kern.proc.pathname to work on 3.8.
However 3.8 is missing the kern.ipc.shm_allow_removed sysctl anyway, which is needed to actually run chromium.

**Comment by jrmarino** [comment]
are you actually able to use chromium at all on dev branch?  the last I heard, it still didn't launch.

**Comment by ivadasz** [comment]
Chromium runs reliably, when I additionally stub out the getframeaddr() function (e.g. always return NULL) in libexecinfo; or by commenting out the backtrace() call in chromium's StackTrace::StackTrace() function in base/debug/stack_trace_posix.cc:744.
For some reason libexecinfo would segfault when trying to generate a stacktrace (Generating a stacktrace seems to be triggered by some assertions within chromium).

**Comment by jrmarino** [comment]
So IIUC, the packaged chromium still does not run.  In addition to removing these obsolete patches, we'd need to add your backtrace disabling patch as well.  Is that accurate?  Should we include that patch?

**Comment by ivadasz** [comment]
yeah, either need to include a patch for disabling backtracing, or we need to figure out where and which compile flags to change to get backtraces working correctly.
So to get chromium running ASAP, we should just add a patch to disable backtraces for now.

**Comment by ivadasz** [comment]
Added the patch, which disables stack tracing in chromium.
This workaround should make chromium work for now.

**Comment by jrmarino** [comment]
I've incorporated this via Deltaports.  It's now in DPorts and packages have been produced for 4.0 and 4.2 repos (but neither has been confirmed yet).

Thanks!

**Pull request closed without merging**
